kind: pipeline
name: default

steps:
  - name: docker-tag-build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: jerheij/drone-server
      no_cache: true
      tags: ${DRONE_TAG}
    when:
      event:
        - tag

  - name: docker-latest-build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: jerheij/drone-server
      no_cache: true
      tags: latest
    when:
      event:
        - push
      branch:
        - master

  - name: docker-stable-build
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: jerheij/drone-server
      no_cache: true
      tags: stable
    when:
      event:
        - cron
        - push
      branch:
        - stable

  - name: matrix_notification_success
    image: spotlightkid/drone-matrixchat-notify
    settings:
      homeserver:
        from_secret: MATRIX_SERVER
      roomid:
        from_secret: MATRIX_ROOM_ID
      userid:
        from_secret: MATRIX_USER_ID
      accesstoken:
        from_secret: MATRIX_ACCESS_TOKEN
      deviceid:
        from_secret: MATRIX_DEVICE_ID
      devicename: 'Drone CI'
      template: |
        ✅ Drone Build ${DRONE_REPO_NAME}/${DRONE_COMMIT_BRANCH} ${DRONE_TAG} ${DRONE_BUILD_STATUS}
        ${DRONE_BUILD_LINK}
    when:
      status: [ success, changed ]

  - name: matrix_notification_failure
    image: spotlightkid/drone-matrixchat-notify
    settings:
      homeserver:
        from_secret: MATRIX_SERVER
      roomid:
        from_secret: MATRIX_ROOM_ID
      userid:
        from_secret: MATRIX_USER_ID
      accesstoken:
        from_secret: MATRIX_ACCESS_TOKEN
      deviceid:
        from_secret: MATRIX_DEVICE_ID
      devicename: 'Drone CI'
      template: |
        🔴 Drone Build ${DRONE_REPO_NAME}/${DRONE_COMMIT_BRANCH} ${DRONE_TAG} ${DRONE_BUILD_STATUS}
        ${DRONE_BUILD_LINK}
    when:
      status: [ failure ]